### ISSUE TITLE
Wrong argument in call to treesit-range-rules

### ISSUE THREAD

**Issue by czw** [Sorixelle/astro-ts-mode#11]
I get this error message when enabling astro-ts-mode in a buffer:

    treesit-range-rules: Wrong type argument: treesit-query-p, :local

Environment: GNU Emacs 29.4 running in macOS 15.2.

The error goes away if I remove the two ```:local t``` lines.

**Comment by Sorixelle** [comment]
Oooh... hmm. 2.0.2 should have been a 3.0.0, if that's happening. Totally forgot to check that when I cut that release, apologies.

I'm hesitant to do anything to roll that back, because in my experience TS interpolation highlighting gets pretty messy without it. It is a feature of newer Emacs though unfortunately, so the best fix would probably be to either rollback astro-ts-mode (f80c2a4832e907ae1be11c1bd7243fb565b2ec31 should work fine) or update Emacs. I'll see if there's anything I can do about getting that breaking version pulled and released under a major version - and I'll also update the docs to reflect the new Emacs version requirements.

**Comment by czw** [comment]
Switching to the latest testing version (Emacs 30.0.93) seems to do the trick. Works beautifully now, so thanks for putting in the work to implement this!

**Comment by Sorixelle** [comment]
Version bump done, 2.0.2 tag removed and everything updated to state minimum Emacs 30 instead of 29. Thanks for the heads up!
