### ISSUE TITLE
`treesit-ready-p` is not available

### ISSUE THREAD

**Issue by ronniedroid** [Sorixelle/astro-ts-mode#3]
I am on emacs version 29.0.92, compiled form source form the emacs git repo. using the emacs-29 branch.

the `(treesit-ready-p 'lang)` does not exist.
Had to change it to `(treesit-language-available-p 'lang)` for it to work.
On lines: 177, 180, 183 and 218.

**Comment by Sorixelle** [comment]
I'm not able to reproduce this on this version of Emacs. Can you post the value of both `system-configuration-features` and `system-configuration-options` in your build?

**Comment by ronniedroid** [comment]
features:
```
"CAIRO DBUS FREETYPE GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBSELINUX LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER XIM GTK3 ZLIB"
```
and, options:
```
"--without-compress-install --with-native-compilation --with-json --with-mailutils --with-pgtk --with-tree-sitter --with-rsvg"
```

please not that the command does work and is available to me in my emacs before I activate `astro-ts-mode`, after that, the command is no longer available.

**Comment by Sorixelle** [comment]
Figured out the issue - `treesit-ready-p` doesn't have an autoload, so the `auto-mode-alist` assignment I had on load was failing. I've removed those autoloads, so that should fix the issue. You'll need to make sure you `(require 'astro-ts-mode)` if you were relying on this mode to setup the file association for you.
